version: '2.0'
services:
  botrs:
    ports:
      - "3001:3000"
  db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: arstarst
      POSTGRES_DB: db
    ports:
      - "5433:5432"
