version: '2.0'
services:
  botrs:
    build: ./bot-rs/
    image: emallson/gladiator-bot-discord:latest
    env_file: ./bot-rs/.env
    depends_on:
      - db
  db:
    build: './db-setup/'
    image: emallson/gladiator-bot-db:latest
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
