version: '2.0'
services:
  botrs:
    build: ./bot-rs/
    env_file: ./bot-rs/.env
    depends_on:
      - db
  db:
    build: './db-setup/'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: arstarst
      POSTGRES_DB: db
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
