FROM rust
RUN apt-get update && apt-get install -y libpq5 pgloader
WORKDIR /opt/bot
COPY dummy.rs .
COPY Cargo.toml .
COPY Cargo.lock .
RUN sed -i 's/src/main.rs/dummy.rs/' Cargo.toml
RUN cargo build --release
RUN sed -i 's/dummy.rs/src/main.rs/' Cargo.toml
COPY . .
RUN cargo build --release
CMD cargo run --release